### PR TITLE
Rails 4

### PR DESCRIPTION
**Pull request by sahilm**
Hello Folks,

I ran into a small issue while attempting to use spork-rails with a rails 4 project. I don't really think my pull request contains everything required to support rails 4 but I've tried to make a start.

Do let me know what you guys think.

Thanks.

### CODE REVIEW

**Comment by arthurnn** [comment]
+1 on this feature.

**Comment by whatthewhat** [comment]
+1
sahilm's fork works for me on current rails 4 master

**Comment by arthurnn** [comment]
I have those changes running in beta project for a month, and no problems so far.

**Comment by jasnow** [comment]
I need this too to upgrade to Rails 4.0

**Comment by threadhead** [comment]
+1, with a pretty please

**Comment by cykhoo** [comment]
+1 - would be great to have this now Rails 4 beta is out!

**Comment by mhartl** [comment]
+1. This is currently preventing me from incorporating Spork into the Rails 4 draft of the Ruby on Rails Tutorial.

**Comment by ekampp** [comment]
:+1:

**Comment by bwobst** [comment]
+1 and +1 to mhartl for working on a Rails 4 version of the tutorial!

**Comment by tetherit** [comment]
+1 still no rails 4 support? :(

**Comment by koriroys** [comment]
My fix: https://github.com/koriroys/spork-rails/commit/355a354e9de328e86a9f3fe306f243745950a7d1

**Comment by koriroys** [comment]
@bwobst does your gemfile look like this?

``` ruby
gem 'spork-rails', git: 'git://github.com/koriroys/spork-rails.git'
```

and you are running `bundle update spork-rails`

Cheers

**Comment by bwobst** [comment]
@koriroys Gemfile looks like that now!  Returns "Couldn't find gem 'spork-rails'".  Also, 'git clone' fails when doing 'bundle update' by itself.

**Comment by jarijokinen** [comment]
Forks by @sahilm or @koriroys are not working anymore with Rails 4.0.0.beta1 (or master), Ruby 2.0.0 p0 and RSpec.

```
$ bundle exec spork
Using RSpec, Rails
Preloading Rails environment
Loading Spork.prefork block...
undefined method `sub' for nil:NilClass (NoMethodError)
```

Full stack trace: https://gist.github.com/jarijokinen/5180864

Gemfile is the initial file generated by the "rails new" command, with these additions:

```
gem "rspec-rails"
gem "spork-rails", github: "koriroys/spork-rails"
```

The weird thing is that this worked fine earlier, but suddenly stopped working.

Any ideas how to fix this?

**Comment by kennyj** [comment]
Hi @jarijokinen 
It seems that this is related to #16 .

**Comment by josemotanet** [comment]
Any updates on this? I'm currently working on a course for Tuts+ Premium with Spork and would love this to work.

**Comment by timdorr** [comment]
Now that Rails 4 is out, is anyone going to merge this? It seems the Spork folks are asleep at the wheel :unamused:

**Comment by kostia** [comment]
+1 Please merge and release ASAP.

**Comment by kirkonrails** [comment]
+1

**Comment by nixme** [comment]
Hi guys, not sure if @timcharper has had much time to work on spork lately. I know I haven't on the spork-testunit side.

As a current solution, I suggest people try https://github.com/jonleighton/spring

**Comment by kathgironpe** [comment]
+1 please merge this. Thank you.

**Comment by kanfet** [comment]
+1

**Comment by sahilm** [comment]
I authored this pull request 6 months ago. Clearly the people maintaing spork-rails have moved on to other things. As @nixme has already mentioned, there are new tools to do this kind of stuff like Zeus, Spring and Commands. I would suggest watching episode [#412 Fast Rails Commands](http://railscasts.com/episodes/412-fast-rails-commands?autoplay=true) of the excellent [RailsCasts](http://railscasts.com/) for a rundown on all of these new tools.

Cheers.

**Comment by timcharper** [comment]
I have not been receiving github notifications, I'm not sure why. Anyways, yes, I've moved on, I haven't worked on a ruby-on-rails project for several years, and consequently, a project that would need a solution as spork.

Happy to hand the reigns over to somebody. But if it would be better, I can just shut it down and refer people to the other tools.

**Comment by timcharper** [comment]
@sahilm you have github access.

**Comment by sahilm** [comment]
@timcharper Thanks for granting me GitHub access. I will revise my implementation and make a commit soon. Also, I don't mind taking a stab at maintaing spork.

**Comment by mat813** [comment]
@sahilm :+1:

**Comment by amalc** [comment]
@sahilm :+1:

**Comment by sahilm** [comment]
Support for Rails 4, Ruby 2.0, Cucumber 1.3.2 and Rspec 2.13.0 has landed on master. Please help me test by including `spork-rails, :github => 'sporkrb/spork-rails'` in your Gemfile.

CI builds for spork and spork-rails have been setup at https://travis-ci.org/sporkrb/spork and https://travis-ci.org/sporkrb/spork-rails respectively.

I'm going to send out an email to @timcharper requesting RubyGems access.

Thanks.

**Comment by kanfet** [comment]
> Please help me test by including spork-rails, :github => 'sporkrb/spork-rails' in your Gemfile.

It works in my application on Rails 4, Ruby 2.0 and Rspec 2.13.2!

**Comment by cschiewek** [comment]
Works fine, even with guard-spork.

**Comment by kanfet** [comment]
I use spork-rails with guard-spork in my application. 
I tested it one minute ago again. It works with guard-spork 1.5.1

**Comment by railstutorial** [comment]
Guard appears to work OK on my system with

``` ruby
  gem 'guard-rspec', '2.5.0'
  gem 'spork-rails', github: 'sporkrb/spork-rails'
  gem 'guard-spork', '1.5.0'
```

**Comment by ghost** [comment]
I was having a really hard time with this, but I finally got rails 4, spork, rspec, and guard working after I read this:

http://stackoverflow.com/questions/14791957/guard-spork-rspec-issue-how-do-i-remove-hooks-to-testunit

**Comment by railstutorial** [comment]
I think this should only happen if there's a `test` directory. Does it happen for you in any case? I can't reproduce the issue on my system.

**Comment by ghost** [comment]
No, you're right.  It happened because I DO have a test directory.  Once I deleted it, it worked fine.  But since I have other tests in that directory, I didn't want to delete it.  So I was able to get it working by supplying the :test_unit=>false option to the Spork block in my Guardfile.

```
guard 'spork', :test_unit=>false do
  ...
end
```

**Comment by kathgironpe** [comment]
@sahilm thank you

**Comment by sahilm** [comment]
Just released spork-rails 4.0.0 to RubyGems. It's no longer necessary to pull the gem from GitHub.

**Comment by cykhoo** [comment]
Thank you very much!

**Comment by kanfet** [comment]
Thank you!

**Pull request closed without merging**
