### PR TITLE
Adding note about --drb option for rspec

### PR DESCRIPTION
**Pull request by msaspence**

### CODE REVIEW

**Comment by BMorearty** [comment]
Please pull this request. It's a helpful doc change. It helped me figure out why spork-rails was not working in my app.

**Comment by jazminschroeder** [comment]
Very useful info in this pull request, If you need help merging this stuff I'd be happy to help.

**Comment by arthurnn** [comment]
:+1: 

First time using spork I was really confused because didnt realize that I had to use the --drb option.

**Comment by sahilm** [comment]
Thanks.

**Pull request merged**
